export default [
  {
    id: 1,
    title: 'FlexBox Help',
    description: 'About Use to solve how to center a div and all css flexbox by just checking the apporiate style the code automatic generate for you.',
    image: './img/projects/flexbox.jpg',
    type: '/ Branding + Website',
    url: 'https://flexbox.lol',
    html: 'true',
    css: 'true',
    bs: 'false',
    js: 'true',
    php: 'false',
    wp: 'false',
    rt: 'true',
    git: 'true',
    repl: 'true',
    node: 'true'
  },
  {
    id: 2,
    title: 'Idris Design',
    description: 'Idris Design is a UI Engineer Portfolio . I use nice Animation, Typography, Color, layer, background, &amp; more to introduce what Idris Service are to his viewers',
    image: './img/projects/dysgner-idris.jpg',
    type: '/ Branding + Website',
    url: 'https://idris.design',
    html: 'true',
    css: 'true',
    bs: 'false',
    js: 'true',
    php: 'false',
    wp: 'false',
    rt: 'true',
    git: 'true',
    repl: 'true',
    node: 'true'
  },
  {
    id: 3,
    title: 'NameTheater',
    description: 'NameTheater ia a name generation company. I Design the website, Logo, and build the website I use nice images and when you hover on few images it change to another one and the hero rocket launch immediately scroll down',
    image: './img/projects/nametheater.jpg',
    type: '/ Branding + Website',
    url: 'https://nametheater.com',
    html: 'true',
    css: 'true',
    bs: 'false',
    js: 'true',
    php: 'false',
    wp: 'false',
    rt: 'true',
    git: 'true',
    repl: 'true',
    node: 'true'
  },
  {
    id: 4,
    title: 'NYTypical',
    description: 'I build a fashion Portfolio for a start up brand I make the Website in minimalis style i use very attractive Typography, images, color, layer, animation',
    image: './img/projects/nytypical.jpg',
    type: '/ Branding + Website',
    url: 'https://idris.design',
    html: 'true',
    css: 'true',
    bs: 'false',
    js: 'true',
    php: 'false',
    wp: 'false',
    rt: 'true',
    git: 'true',
    repl: 'true',
    node: 'true'
  },
  {
    id: 5,
    title: 'Paint It Right',
    description: 'Paint it Right is a Paint Company Theme I code the single-page application website using paint bucket as a carousel Control button Next &amp; Prev , Use Typography, Nice Colors, Nice Fonts, and more',
    image: './img/projects/painittight.jpg',
    type: '/ Branding + Website',
    url: 'https://biadedigital.github.io/PaintItRight/',
    html: 'true',
    css: 'true',
    bs: 'false',
    js: 'true',
    php: 'false',
    wp: 'false',
    rt: 'true',
    git: 'true',
    repl: 'true',
    node: 'true'
  },{
    id: 6,
    title: 'Adrad Event Centre',
    description: 'Adrad Event Centre is an event venue hall for public performances. I design and build Adrad Website to showcase their services and solve user problems From the website they get adequate information to the Hall',
    image: './img/projects/adradevent.jpg',
    type: '/ Branding + Website',
    url: 'https://adradeventcenter.com/',
    html: 'true',
    css: 'true',
    bs: 'false',
    js: 'true',
    php: 'false',
    wp: 'false',
    rt: 'true',
    git: 'true',
    repl: 'true',
    node: 'true'
  },
  {
    id: 7,
    title: 'FlowTunz',
    description: 'FlowTunz is an E-Commerce company that trades Cryptocurrency /Digital-Currency to Fiat. I Developed a Nice UI Friendly website for the user with chat desk support for the user to reach out to the admin',
    image: './img/projects/flowtunz.jpg',
    type: '/ Branding + Website Expired',
    url: '#',
    html: 'true',
    css: 'true',
    bs: 'false',
    js: 'true',
    php: 'false',
    wp: 'false',
    rt: 'true',
    git: 'true',
    repl: 'true',
    node: 'true'
  },
  {
    id: 8,
    title: 'FoodGo',
    description: 'FoodGo is an E-commerce website you can add products to cart and setup account. I hard code the E-Commerce website all pages Home, About, Store, Contact, Account, Sign up, Checkout, Sign In and More',
    image: './img/projects/foodgo.jpg',
    type: '/ Branding + Website',
    url: 'https://biadedigital.github.io/FoodGo/',
    html: 'true',
    css: 'true',
    bs: 'false',
    js: 'true',
    php: 'false',
    wp: 'false',
    rt: 'true',
    git: 'true',
    repl: 'true',
    node: 'true'
  },
   {
    id: 9,
    title: 'stylish',
    description: 'Hard code an E-commerce Website with a hover mega menu to display all product categories as a menu item  and make them responsive I also use hover on the card to make it user-friendly to add to cart and color variable to change the  image',
    image: './img/projects/stylish.jpg',
    type: '/ Branding + Website',
    url: 'https://biadedigital.github.io/stylish',
    html: 'true',
    css: 'true',
    bs: 'false',
    js: 'true',
    php: 'false',
    wp: 'false',
    rt: 'true',
    git: 'true',
    repl: 'true',
    node: 'true'
  },
   {
    id: 10,
    title: 'FoodGo',
    description: 'FoodGo is an E-commerce website you can add products to cart and setup account. I hard code the E-Commerce website all pages Home, About, Store, Contact, Account, Sign up, Checkout, Sign In and More',
    image: './img/projects/card.jpg',
    type: '/ Branding + Website',
    url: 'https://biadedigital.github.io/FoodGo/',
    html: 'true',
    css: 'true',
    bs: 'false',
    js: 'true',
    php: 'false',
    wp: 'false',
    rt: 'true',
    git: 'true',
    repl: 'true',
    node: 'true'
  }

]


