export default [
  {
    id: 1,
    title: 'InclusivelyRemote',
    description: 'Inclusively Remote is a Recruitment agency. I use nice Animation, Typography, Color, layer, background, &amp; more to introduce what InclusivelyRemote Service is to his viewers',
    image: './img/projects/inclusivelyRemote.jpg',
    type: '/ Branding + Website',
    url: 'https://flexbox.lol',
    html: true,
    css: true,
    bs: false,
    js: true,
    php: false,
    wp: false,
    rt: true,
    git: true,
    repl: true,
    node: true,
    status: 'Online'
  },
  {
    id: 2,
    title: 'FlexBox Help',
    description: 'Use CSS FlexBox Help this website to solve all your flexbox issues like how to center a div by just selecting the appropriate style the code automatically generated for you.',
    image: './img/projects/flexbox.jpg',
    type: '/ Branding + Website',
    url: 'https://flexbox.lol',
    html: '1',
    css: true,
    bs: false,
    js: true,
    php: false,
    wp: false,
    rt: true,
    git: true,
    repl: true,
    node: true,
    status: 'Online'
  },
  {
    id: 3,
    title: 'Idris Design',
    description: 'Idris Design is a UI Engineer Portfolio . I use nice Animation, Typography, Color, layer, background, &amp; more to introduce what Idris Service are to his viewers',
    image: './img/projects/dysgner-idris.jpg',
    type: '/ Branding + Website',
    url: 'https://idris.design',
    html: true,
    css: true,
    bs: false,
    js: true,
    php: false,
    wp: false,
    rt: true,
    git: true,
    repl: true,
    node: true,
    status: 'Online'
  },
  {
    id: 4,
    title: 'NameTheater',
    description: 'NameTheater ia a name generation company. I Design the website, Logo, and build the website I use nice images and when you hover on few images it change to another one and the hero rocket launch immediately scroll down',
    image: './img/projects/nametheater.jpg',
    type: '/ Branding + Website',
    url: 'https://nametheater.com',
    html: true,
    css: true,
    bs: false,
    js: true,
    php: false,
    wp: false,
    rt: true,
    git: true,
    repl: true,
    node: true,
    status: 'Online'
  },
  {
    id: 5,
    title: 'NYTypical',
    description: 'I build a fashion Portfolio for a start up brand I make the Website in minimalis style i use very attractive Typography, images, color, layer, animation',
    image: './img/projects/nytypical.jpg',
    type: '/ Branding + Website',
    url: 'https://idris.design',
    html: true,
    css: true,
    bs: false,
    js: true,
    php: false,
    wp: false,
    rt: true,
    git: true,
    repl: true,
    node: true,
    status: 'Online'
  },
  {
    id: 6,
    title: 'Paint It Right',
    description: 'Paint it Right is a Paint Company Theme I code the single-page application website using paint bucket as a carousel Control button Next &amp; Prev , Use Typography, Nice Colors, Nice Fonts, and more',
    image: './img/projects/painittight.jpg',
    type: '/ Branding + Website',
    url: 'https://biadedigital.github.io/PaintItRight/',
    html: true,
    css: true,
    bs: false,
    js: true,
    php: false,
    wp: false,
    rt: true,
    git: true,
    repl: true,
    node: true,
    status: 'Online'
  },
  {
    id: 7,
    title: 'Adrad Hall',
    description: 'Adrad Event Centre is an event venue hall for public performances. I design and build Adrad Website to showcase their services and solve user problems From the website they get adequate information to the Hall',
    image: './img/projects/adradevent.jpg',
    type: '/ Branding + Website',
    url: 'https://adradeventcenter.com/',
    html: '1',
    css: '1',
    bs: '0',
    js: '1',
    php: '0',
    wp: '0',
    rt: '1',
    git: '1',
    repl: '1',
    node: '1',
    status: 'Online'
  },
  {
    id: 8,
    title: 'FlowTunz',
    description: 'FlowTunz is an E-Commerce company that trades Cryptocurrency /Digital-Currency to Fiat. I Developed a Nice UI Friendly website for the user with chat desk support for the user to reach out to the admin',
    image: './img/projects/flowtunz.jpg',
    type: '/ Branding + Website Expired',
    url: '#',
    html: '1',
    css: '1',
    bs: '0',
    js: '1',
    php: '0',
    wp: '0',
    rt: '1',
    git: '1',
    repl: '1',
    node: '1',
    status: 'Online'
  },
  {
    id: 9,
    title: 'FoodGo',
    description: 'FoodGo is an E-commerce website you can add products to cart and setup account. I hard code the E-Commerce website all pages Home, About, Store, Contact, Account, Sign up, Checkout, Sign In and More',
    image: './img/projects/foodgo.jpg',
    type: '/ Branding + Website',
    url: 'https://biadedigital.github.io/FoodGo/',
    html: '1',
    css: '1',
    bs: '0',
    js: '1',
    php: '0',
    wp: '0',
    rt: '1',
    git: '1',
    repl: '1',
    node: '1',
    status: 'Online'
  },
  {
    id: 10,
    title: 'stylish',
    description: 'Hard code an E-commerce Website with a hover mega menu to display all product categories as a menu item  and make them responsive I also use hover on the card to make it user-friendly to add to cart and color variable to change the  image',
    image: './img/projects/stylish.jpg',
    type: '/ Branding + Website',
    url: 'https://biadedigital.github.io/stylish',
    html: '1',
    css: '1',
    bs: '0',
    js: '1',
    php: '0',
    wp: '0',
    rt: '1',
    git: '1',
    repl: '1',
    node: '1',
    status: 'Online'
  },
  {
    id: 11,
    title: 'FoodGo',
    description: 'FoodGo is an E-commerce website you can add products to cart and setup account. I hard code the E-Commerce website all pages Home, About, Store, Contact, Account, Sign up, Checkout, Sign In and More',
    image: './img/projects/card.jpg',
    type: '/ Branding + Website',
    url: 'https://biadedigital.github.io/FoodGo/',
    html: '1',
    css: '1',
    bs: '0',
    js: '1',
    php: '0',
    wp: '0',
    rt: '1',
    git: '1',
    repl: '1',
    node: '1',
    status: 'Online'
  }

]


